#pragma once

#include <string>
#include <unordered_map>
#include <unordered_set>


const std::unordered_map<char, std::wstring> charToLetters{
    {'A', L"на"  },
    {'B', L"роз"},
    {'C', L"ви"  },
    {'D', L"пер"},
    {'E', L"при"},
    {'F', L"у"    },
    {'G', L"про"},
    {'H', L"об"  },
    {'I', L"не"  },
    {'J', L"ш"    },
    {'K', L"л"    },
    {'L', L"від"},
    {'M', L"ко"  },
    {'N', L"під"},
    {'O', L"до"  },
    {'P', L"х"    },
    {'Q', L"ф"    },
    {'R', L"ч"    },
    {'S', L"ст"  },
    {'T', L"ка"  },
    {'U', L"па"  },
    {'V', L"од"  },
    {'W', L"ма"  },
    {'X', L"ба"  },
    {'Y', L"і"    },
    {'Z', L"е"    },
    {'a', L"сп"  },
    {'b', L"ск"  },
    {'c', L"тр"  },
    {'d', L"бе"  },
    {'e', L"поп"},
    {'f', L"са"  },
    {'g', L"те"  },
    {'h', L"де"  },
    {'i', L"ц"    },
    {'j', L"я"    },
    {'k', L"поз"},
    {'l', L"кр"  },
    {'m', L"га"  },
    {'n', L"го"  },
    {'o', L"ре"  },
    {'p', L"су"  },
    {'q', L"пов"},
    {'r', L"во"  },
    {'s', L"пос"},
    {'t', L"мо"  },
    {'u', L"со"  },
    {'v', L"се"  },
    {'w', L"ку"  },
    {'x', L"ж"    },
    {'y', L"ос"  },
    {'z', L"си"  },
    {'0', L"бо"  },
    {'1', L"ве"  },
    {'2', L"бу"  },
    {'3', L"гр"  },
    {'4', L"щ"    },
    {'5', L"зас"},
    {'6', L"ра"  },
    {'7', L"зак"},
    {'8', L"ан"  },
    {'9', L"зап"},
    {'+', L"то"  },
    {'/', L"пор"},
    {'=', L"ме"  },

    // {static_cast<char>(0),    L"роз"},
    // {static_cast<char>(1),    L"пер"},
    // {static_cast<char>(2),    L"при"},
    // {static_cast<char>(3),    L"про"},
    // {static_cast<char>(4),    L"від"},
    // {static_cast<char>(5),    L"під"},
    // {static_cast<char>(6),    L"поп"},
    // {static_cast<char>(7),    L"поз"},
    // {static_cast<char>(8),    L"ре"  },
    // {static_cast<char>(9),    L"пов"},
    // {static_cast<char>(10),   L"пос"},
    // {static_cast<char>(11),   L"мо"  },
    // {static_cast<char>(12),   L"ку"  },
    // {static_cast<char>(13),   L"ос"  },
    // {static_cast<char>(14),   L"зас"},
    // {static_cast<char>(15),   L"зак"},
    // {static_cast<char>(16),   L"зап"},
    // {static_cast<char>(17),   L"пор"},
    // {static_cast<char>(18),   L"пол"},
    // {static_cast<char>(19),   L"мі"  },
    // {static_cast<char>(20),   L"ва"  },
    // {static_cast<char>(21),   L"та"  },
    // {static_cast<char>(22),   L"над"},
    // {static_cast<char>(23),   L"без"},
    // {static_cast<char>(24),   L"нап"},
    // {static_cast<char>(25),   L"пон"},
    // {static_cast<char>(26),   L"заг"},
    // {static_cast<char>(27),   L"стр"},
    // {static_cast<char>(28),   L"зв"  },
    // {static_cast<char>(29),   L"бр"  },
    // {static_cast<char>(30),   L"нас"},
    // {static_cast<char>(31),   L"ла"  },
    // {static_cast<char>(32),   L"лі"  },
    // {static_cast<char>(33),   L"ге"  },
    // {static_cast<char>(34),   L"най"},
    // {static_cast<char>(35),   L"пок"},
    // {static_cast<char>(36),   L"кон"},
    // {static_cast<char>(37),   L"ша"  },
    // {static_cast<char>(38),   L"зат"},
    // {static_cast<char>(39),   L"сам"},
    // {static_cast<char>(40),   L"ди"  },
    // {static_cast<char>(41),   L"зам"},
    // {static_cast<char>(42),   L"ста"},
    // {static_cast<char>(43),   L"под"},
    // {static_cast<char>(44),   L"ус"  },
    // {static_cast<char>(45),   L"нед"},
    // {static_cast<char>(46),   L"фа"  },
    // {static_cast<char>(47),   L"спо"},
    // {static_cast<char>(48),   L"пар"},
    // {static_cast<char>(49),   L"ру"  },
    // {static_cast<char>(50),   L"кл"  },
    // {static_cast<char>(51),   L"пот"},
    // {static_cast<char>(52),   L"ле"  },
    // {static_cast<char>(53),   L"хо"  },
    // {static_cast<char>(54),   L"зб"  },
    // {static_cast<char>(55),   L"зав"},
    // {static_cast<char>(56),   L"гу"  },
    // {static_cast<char>(57),   L"ту"  },
    // {static_cast<char>(58),   L"ок"  },
    // {static_cast<char>(59),   L"заб"},
    // {static_cast<char>(60),   L"сл"  },
    // {static_cast<char>(61),   L"вис"},
    // {static_cast<char>(62),   L"ар"  },
    // {static_cast<char>(63),   L"кор"},
    // {static_cast<char>(64),   L"зо"  },
    // {static_cast<char>(65),   L"др"  },
    // {static_cast<char>(66),   L"зд"  },
    // {static_cast<char>(67),   L"поо"},
    // {static_cast<char>(68),   L"пу"  },
    // {static_cast<char>(69),   L"фі"  },
    // {static_cast<char>(70),   L"щон"},
    // {static_cast<char>(71),   L"хр"  },
    // {static_cast<char>(72),   L"кар"},
    // {static_cast<char>(73),   L"ха"  },
    // {static_cast<char>(74),   L"неп"},
    // {static_cast<char>(75),   L"ут"  },
    // {static_cast<char>(76),   L"зм"  },
    // {static_cast<char>(77),   L"сі"  },
    // {static_cast<char>(78),   L"якн"},
    // {static_cast<char>(79),   L"ант"},
    // {static_cast<char>(80),   L"нев"},
    // {static_cast<char>(81),   L"кі"  },
    // {static_cast<char>(82),   L"ти"  },
    // {static_cast<char>(83),   L"пом"},
    // {static_cast<char>(84),   L"ло"  },
    // {static_cast<char>(85),   L"ско"},
    // {static_cast<char>(86),   L"нов"},
    // {static_cast<char>(87),   L"ри"  },
    // {static_cast<char>(88),   L"тра"},
    // {static_cast<char>(89),   L"гл"  },
    // {static_cast<char>(90),   L"см"  },
    // {static_cast<char>(91),   L"ли"  },
    // {static_cast<char>(92),   L"пог"},
    // {static_cast<char>(93),   L"ми"  },
    // {static_cast<char>(94),   L"чер"},
    // {static_cast<char>(95),   L"ши"  },
    // {static_cast<char>(96),   L"рі"  },
    // {static_cast<char>(97),   L"ше"  },
    // {static_cast<char>(98),   L"уп"  },
    // {static_cast<char>(99),   L"три"},
    // {static_cast<char>(100),  L"му"  },
    // {static_cast<char>(101),  L"бл"  },
    // {static_cast<char>(102),  L"нак"},
    // {static_cast<char>(103),  L"рад"},
    // {static_cast<char>(104),  L"ча"  },
    // {static_cast<char>(105),  L"шт"  },
    // {static_cast<char>(106),  L"обс"},
    // {static_cast<char>(107),  L"баг"},
    // {static_cast<char>(108),  L"нав"},
    // {static_cast<char>(109),  L"зг"  },
    // {static_cast<char>(110),  L"зад"},
    // {static_cast<char>(111),  L"вс"  },
    // {static_cast<char>(112),  L"ком"},
    // {static_cast<char>(113),  L"ду"  },
    // {static_cast<char>(114),  L"фе"  },
    // {static_cast<char>(115),  L"ур"  },
    // {static_cast<char>(116),  L"ук"  },
    // {static_cast<char>(117),  L"кол"},
    // {static_cast<char>(118),  L"є"    },
    // {static_cast<char>(119),  L"зал"},
    // {static_cast<char>(120),  L"ал"  },
    // {static_cast<char>(121),  L"пи"  },
    // {static_cast<char>(122),  L"вер"},
    // {static_cast<char>(123),  L"зл"  },
    // {static_cast<char>(124),  L"тер"},
    // {static_cast<char>(125),  L"сто"},
    // {static_cast<char>(126),  L"сте"},
    // {static_cast<char>(127),  L"зах"},
    // {static_cast<char>(-128), L"наг"},
    // {static_cast<char>(-1),   L"гор"},
    // {static_cast<char>(-2),   L"еле"},
    // {static_cast<char>(-3),   L"авт"},
    // {static_cast<char>(-4),   L"вп"  },
    // {static_cast<char>(-5),   L"ді"  },
    // {static_cast<char>(-6),   L"обл"},
    // {static_cast<char>(-7),   L"мал"},
    // {static_cast<char>(-8),   L"ор"  },
    // {static_cast<char>(-9),   L"да"  },
    // {static_cast<char>(-10),  L"от"  },
    // {static_cast<char>(-11),  L"ци"  },
    // {static_cast<char>(-12),  L"чу"  },
    // {static_cast<char>(-13),  L"обм"},
    // {static_cast<char>(-14),  L"поб"},
    // {static_cast<char>(-15),  L"ки"  },
    // {static_cast<char>(-16),  L"зар"},
    // {static_cast<char>(-17),  L"нез"},
    // {static_cast<char>(-18),  L"кри"},
    // {static_cast<char>(-19),  L"шк"  },
    // {static_cast<char>(-20),  L"шу"  },
    // {static_cast<char>(-21),  L"пре"},
    // {static_cast<char>(-22),  L"вт"  },
    // {static_cast<char>(-23),  L"дос"},
    // {static_cast<char>(-24),  L"пла"},
    // {static_cast<char>(-25),  L"нам"},
    // {static_cast<char>(-26),  L"тел"},
    // {static_cast<char>(-27),  L"заш"},
    // {static_cast<char>(-28),  L"хл"  },
    // {static_cast<char>(-29),  L"це"  },
    // {static_cast<char>(-30),  L"лу"  },
    // {static_cast<char>(-31),  L"сві"},
    // {static_cast<char>(-32),  L"гол"},
    // {static_cast<char>(-33),  L"мар"},
    // {static_cast<char>(-34),  L"спі"},
    // {static_cast<char>(-35),  L"ум"  },
    // {static_cast<char>(-36),  L"шп"  },
    // {static_cast<char>(-37),  L"зе"  },
    // {static_cast<char>(-38),  L"скр"},
    // {static_cast<char>(-39),  L"обр"},
    // {static_cast<char>(-40),  L"гра"},
    // {static_cast<char>(-41),  L"ву"  },
    // {static_cast<char>(-42),  L"вип"},
    // {static_cast<char>(-43),  L"нар"},
    // {static_cast<char>(-44),  L"сер"},
    // {static_cast<char>(-45),  L"ак"  },
    // {static_cast<char>(-46),  L"нат"},
    // {static_cast<char>(-47),  L"зр"  },
    // {static_cast<char>(-48),  L"ул"  },
    // {static_cast<char>(-49),  L"лю"  },
    // {static_cast<char>(-50),  L"чи"  },
    // {static_cast<char>(-51),  L"зі"  },
    // {static_cast<char>(-52),  L"пра"},
    // {static_cast<char>(-53),  L"дво"},
    // {static_cast<char>(-54),  L"біл"},
    // {static_cast<char>(-55),  L"пал"},
    // {static_cast<char>(-56),  L"сол"},
    // {static_cast<char>(-57),  L"вк"  },
    // {static_cast<char>(-58),  L"одн"},
    // {static_cast<char>(-59),  L"кв"  },
    // {static_cast<char>(-60),  L"ю"    },
    // {static_cast<char>(-61),  L"уг"  },
    // {static_cast<char>(-62),  L"пс"  },
    // {static_cast<char>(-63),  L"дов"},
    // {static_cast<char>(-64),  L"кра"},
    // {static_cast<char>(-65),  L"ска"},
    // {static_cast<char>(-66),  L"доп"},
    // {static_cast<char>(-67),  L"наб"},
    // {static_cast<char>(-68),  L"вик"},
    // {static_cast<char>(-69),  L"вол"},
    // {static_cast<char>(-70),  L"ув"  },
    // {static_cast<char>(-71),  L"кал"},
    // {static_cast<char>(-72),  L"тор"},
    // {static_cast<char>(-73),  L"спр"},
    // {static_cast<char>(-74),  L"нес"},
    // {static_cast<char>(-75),  L"син"},
    // {static_cast<char>(-76),  L"нал"},
    // {static_cast<char>(-77),  L"пох"},
    // {static_cast<char>(-78),  L"зач"},
    // {static_cast<char>(-79),  L"бар"},
    // {static_cast<char>(-80),  L"ог"  },
    // {static_cast<char>(-81),  L"ни"  },
    // {static_cast<char>(-82),  L"нео"},
    // {static_cast<char>(-83),  L"шл"  },
    // {static_cast<char>(-84),  L"жи"  },
    // {static_cast<char>(-85),  L"пан"},
    // {static_cast<char>(-86),  L"ке"  },
    // {static_cast<char>(-87),  L"пош"},
    // {static_cast<char>(-88),  L"ні"  },
    // {static_cast<char>(-89),  L"бор"},
    // {static_cast<char>(-90),  L"бур"},
    // {static_cast<char>(-91),  L"скл"},
    // {static_cast<char>(-92),  L"доб"},
    // {static_cast<char>(-93),  L"обк"},
    // {static_cast<char>(-94),  L"дер"},
    // {static_cast<char>(-95),  L"фл"  },
    // {static_cast<char>(-96),  L"екс"},
    // {static_cast<char>(-97),  L"фр"  },
    // {static_cast<char>(-98),  L"дом"},
    // {static_cast<char>(-99),  L"зне"},
    // {static_cast<char>(-100), L"ам"  },
    // {static_cast<char>(-101), L"аг"  },
    // {static_cast<char>(-102), L"бал"},
    // {static_cast<char>(-103), L"вг"  },
    // {static_cast<char>(-104), L"док"},
    // {static_cast<char>(-105), L"мет"},
    // {static_cast<char>(-106), L"чор"},
    // {static_cast<char>(-107), L"гал"},
    // {static_cast<char>(-108), L"інт"},
    // {static_cast<char>(-109), L"уд"  },
    // {static_cast<char>(-110), L"вм"  },
    // {static_cast<char>(-111), L"вел"},
    // {static_cast<char>(-112), L"хв"  },
    // {static_cast<char>(-113), L"жа"  },
    // {static_cast<char>(-114), L"чот"},
    // {static_cast<char>(-115), L"обв"},
    // {static_cast<char>(-116), L"гід"},
    // {static_cast<char>(-117), L"тру"},
    // {static_cast<char>(-118), L"ас"  },
    // {static_cast<char>(-119), L"поч"},
    // {static_cast<char>(-120), L"оз"  },
    // {static_cast<char>(-121), L"вод"},
    // {static_cast<char>(-122), L"обе"},
    // {static_cast<char>(-123), L"одс"},
    // {static_cast<char>(-124), L"суп"},
    // {static_cast<char>(-125), L"опо"},
    // {static_cast<char>(-126), L"фот"},
    // {static_cast<char>(-127), L"обт"},
};


const std::unordered_set<std::wstring> usedLetters{
    // L"роз", L"пер", L"при", L"про", L"від", L"під", L"поп", L"поз", L"ре",  L"пов", L"пос",
    // L"мо",
    // L"ку",  L"ос",  L"зас", L"зак", L"зап", L"пор", L"пол", L"мі",  L"ва",  L"та",  L"над",
    // L"без",
    // L"нап", L"пон", L"заг", L"стр", L"зв",  L"бр",  L"нас", L"ла",  L"лі",  L"ге",  L"най",
    // L"пок",
    // L"кон", L"ша",  L"зат", L"сам", L"ди",  L"зам", L"ста", L"под", L"ус",  L"нед", L"фа",
    // L"спо",
    // L"пар", L"ру",  L"кл",  L"пот", L"ле",  L"хо",  L"зб",  L"зав", L"гу",  L"ту",  L"ок",
    // L"заб",
    // L"сл",  L"вис", L"ар",  L"кор", L"зо",  L"др",  L"зд",  L"поо", L"пу",  L"фі",  L"щон",
    // L"хр",
    // L"кар", L"ха",  L"неп", L"ут",  L"зм",  L"сі",  L"якн", L"ант", L"нев", L"кі",  L"ти",
    // L"пом",
    // L"ло",  L"ско", L"нов", L"ри",  L"тра", L"гл",  L"см",  L"ли",  L"пог", L"ми",  L"чер",
    // L"ши",
    // L"рі",  L"ше",  L"уп",  L"три", L"му",  L"бл",  L"нак", L"рад", L"ча",  L"шт",  L"обс",
    // L"баг",
    // L"нав", L"зг",  L"зад", L"вс",  L"ком", L"ду",  L"фе",  L"ур",  L"ук",  L"кол", L"є", L"зал",
    // L"ал",  L"пи",  L"вер", L"зл",  L"тер", L"сто", L"сте", L"зах", L"наг", L"гор", L"еле",
    // L"авт",
    // L"вп",  L"ді",  L"обл", L"мал", L"ор",  L"да",  L"от",  L"ци",  L"чу",  L"обм", L"поб",
    // L"ки",
    // L"зар", L"нез", L"кри", L"шк",  L"шу",  L"пре", L"вт",  L"дос", L"пла", L"нам", L"тел",
    // L"заш",
    // L"хл",  L"це",  L"лу",  L"сві", L"гол", L"мар", L"спі", L"ум",  L"шп",  L"зе",  L"скр",
    // L"обр",
    // L"гра", L"ву",  L"вип", L"нар", L"сер", L"ак",  L"нат", L"зр",  L"ул",  L"лю",  L"чи", L"зі",
    // L"пра", L"дво", L"біл", L"пал", L"сол", L"вк",  L"одн", L"кв",  L"ю",   L"уг",  L"пс",
    // L"дов",
    // L"кра", L"ска", L"доп", L"наб", L"вик", L"вол", L"ув",  L"кал", L"тор", L"спр", L"нес",
    // L"син",
    // L"нал", L"пох", L"зач", L"бар", L"ог",  L"ни",  L"нео", L"шл",  L"жи",  L"пан", L"ке",
    // L"пош",
    // L"ні",  L"бор", L"бур", L"скл", L"доб", L"обк", L"дер", L"фл",  L"екс", L"фр",  L"дом",
    // L"зне",
    // L"ам",  L"аг",  L"бал", L"вг",  L"док", L"мет", L"чор", L"гал", L"інт", L"уд",  L"вм",
    // L"вел",
    // L"хв",  L"жа",  L"чот", L"обв", L"гід", L"тру", L"ас",  L"поч", L"оз",  L"вод", L"обе",
    // L"одс",
    // L"суп", L"опо", L"фот", L"обт",

    L"на",  L"роз", L"ви",  L"пер", L"при", L"у",  L"про", L"об", L"не",  L"ш",   L"л",
    L"від", L"ко",  L"під", L"до",  L"х",   L"ф",  L"ч",   L"ст", L"ка",  L"па",  L"од",
    L"ма",  L"ба",  L"і",   L"е",   L"сп",  L"ск", L"тр",  L"бе", L"поп", L"са",  L"те",
    L"де",  L"ц",   L"я",   L"поз", L"кр",  L"га", L"го",  L"ре", L"су",  L"пов", L"во",
    L"пос", L"мо",  L"со",  L"се",  L"ку",  L"ж",  L"ос",  L"си", L"бо",  L"ве",  L"бу",
    L"гр",  L"щ",   L"зас", L"ра",  L"зак", L"ан", L"зап", L"то", L"пор", L"ме",
};